apiVersion: v1
kind: Secret
metadata:
  name: games-api-secrets
  namespace: fase4
type: Opaque
stringData:
  jwt-secret: "your-super-secret-key-at-least-32-characters-long!"
  jwt-issuer: "ms-users-api"
  jwt-audience: "ms-users-api-client"
  jwt-key-id: "ms-users-api-signing-key"
  aws-access-key-id: "local"
  aws-secret-access-key: "local"
