apiVersion: v1
kind: ServiceAccount
metadata:
  name: games-api
  namespace: fase4
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::137307165966:role/fase4-games-api-dev-cluster-20260514023828073600000001
