apiVersion: v1
kind: ServiceAccount
metadata:
  name: games-api
  namespace: fase4
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::137307165966:role/fcg-fase4-cluster-20260515004545538000000001
